### ISSUE TITLE
GitHub username invalid

### ISSUE THREAD

**Issue by jordantrainor** [jaebradley/fruit#42]
CLI keeps telling me that my GitHub username is invalid.

**Comment by jaebradley** [comment]
@jordantrainor thanks for opening this issue - do you mind posting a screenshot of the error that you're running into?

**Comment by jordantrainor** [comment]
Hmm sorry, as soon as I did it again to take a screenshot it seemed to work. I kept on getting an error saying that I was entering an invalid GitHub username.
